import "./globals.css";

import Link from "next/link";
import { Control } from "./Control";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by jypark38",
};

export default async function RootLayout({ children }) {
  const res = await fetch(process.env.NEXT_PUBLIC_API_URL + "topics", { cache: "no-cache" });
  // {cache:'no-cache'}를 추가하면 캐쉬를 사용하지 않게 됩니다.

  // 이제 layout.js의 fetch는 랜더링 될 때마다 캐쉬를 사용하지 않고 신선한 데이터를 가져오게 되었습니다.
  const topics = await res.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
